### ISSUE TITLE
Stuck with OTP sent

### ISSUE THREAD

**Issue by niksang** [truroshan/CoWin-Termux#16]
Hi,

Thanks for the code. I tried installing git and other requirements as per the readme.
After installing and running the python script, it gets stuck with "OTP Sent (AutoMode) ...." message. I dont see any message, though i have got an OTP in the phone. Its not able to read the messages i guess. if i do CTRL+C, i see it stuck at file <my mobile nu> not found.

Not sure if anything else needs to be done for it to have permission to read the message.

--
Thanks,
Nikhil

**Comment by truroshan** [comment]
Join https://t.me/CoWIN_Termux
