### ISSUE TITLE
Where did secret come from?

### ISSUE THREAD

**Issue by atTheShikhar** [truroshan/CoWin-Termux#2]
I was just wondering how did you generate the secret that is being sent with the mobile number to get the OTP? 
`
self.data = 
{        "secret":"U2FsdGVkX1+gGN13ULaCVtLSWmsyZwAdXXTIAvLQp2HOXrIBCcq0yyOZQqzzfiFiEYs7KoAOTK2j4qPF/sEVww==",        "mobile": self.mobile_no 
}
`
The one used in official site if different from this one. I tried decoding with base64 but the response was not readable. 
Thanks

**Comment by truroshan** [comment]
cowin website
