### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by SHEKHAR-SAHU-JAIPUR** [truroshan/CoWin-Termux#5]
Brother i have also created similar code but getting unauthorised access error

**Comment by SHEKHAR-SAHU-JAIPUR** [comment]
import requests
from fake_useragent import UserAgent

url = "https://api.demo.co-vin.in/api/v2/auth/generateOTP"



browser_header = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36',
                  'x-api-key': '3sjOr2rmM52GzhpMHjDEE1kpQeRxwFDr4YcBEimi'}


myobj = {
    "mobile": "8387XXXXX"
    }

x = requests.post(url, json = myobj, headers=browser_header)


txnid = x.text[10:-2] 
print(txnid)


url2 = "https://api.demo.co-vin.in/api/v2/appointment/sessions/findByDistrict?district_id=512&date=31-03-2021&vaccine=COVISHIELD"


#browser_header2 = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36',
                  #'Authorization': f'Bearer {txnid}'}

z = UserAgent().random


browser_header3 = {'User-Agent': f'{z}',
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'en-US,en;q=0.5',
            'Content-Type': 'application/json',
            'Origin': 'https://selfregistration.cowin.gov.in',
            'Connection': 'keep-alive',
            'Referer': 'https://selfregistration.cowin.gov.in/',
            'TE': 'Trailers',
            'Authorization': f'Bearer {txnid}',}

print()
print(browser_header3)
y = requests.get(url2, headers=browser_header3)


print()
print(y.text)

**Comment by SHEKHAR-SAHU-JAIPUR** [comment]
Previous is cleared ,, New Issue - I checked you are using ......cdn-api.co... which is totally protected api ,, how you got API key for the same , i am using ....api.demo.co.. protected , api key free given on cowin website but data is not not real time.
Thank You.

**Comment by truroshan** [comment]
Inspect network activity in Browser

**Comment by SHEKHAR-SAHU-JAIPUR** [comment]
Please sir can you elaborate this please please

**Comment by dgbkn** [comment]
sir can you also tell how did you solved the captacha

**Comment by truroshan** [comment]
![image](https://user-images.githubusercontent.com/45506201/118910687-8da03900-b942-11eb-8e4d-d98940d7ff00.png)

**Comment by truroshan** [comment]
> Please can you elaborate this please please

![image](https://user-images.githubusercontent.com/45506201/118910712-96910a80-b942-11eb-844a-b9ef821fdc79.png)

**Comment by truroshan** [comment]
> can you also tell how did you solved the captacha

Check this repo 

https://github.com/ayushchd/cowin_js_bot

**Comment by dgbkn** [comment]
Ok I understood thanks👍

**Comment by atulmits** [comment]
> also tell how did you solved the captacha

Captcha not required for 45+.
